name: Publish

on:
   push:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: ./src/mpv.net.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build mpv.net build
      working-directory: ./
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
    - name: Upload mpv.net latest
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Mpv-release
        path: ./src/*
        if-no-files-found: error
